### ISSUE TITLE
LAN connection possibilities

### ISSUE THREAD

**Issue by gllmlbrt** [strandborg/AlsavoCtrl#13]
I note that in the protocal you refer to possibility to connect in LAN mode at UDP port 1194.

Is it possible and geenerally how would one go about this ? Have you tested ?

**Comment by strandborg** [comment]
The LAN mode means connecting directly to the heat pump to its local WiFi IP address, instead of going through the servers (that seem to be located in China). You'll need to find the local IP of the heat pump yourself, possibly by looking at the list of connected devices in your WiFi AP or router.

**Comment by gllmlbrt** [comment]
Ok, thanks for getting back, but I was all aware of that. My question was more related to the protocol and how to connect to it. Say I known the IP and all of it. I only add the new IP argument and LAN UDP port, and it will return the same string ?

**Comment by strandborg** [comment]
Yes, exactly. I've noticed that sometimes the local IP refuses to answer but the cloud server works, and vice versa (I suspect the UDP stack in the heatpump is buggy). In any case, the protocol, commands and data returned are identical in both modes.

**Comment by gllmlbrt** [comment]
Thanks I will give it a shot then.
