### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by JonnaI89** [strandborg/AlsavoCtrl#14]
Hi. Total newbe on how to get this to work. Where to start. Is it possible to get a step by step "manual"?

**Comment by strandborg** [comment]
All the documentation is currently in the README file; you'll have to find the IP address of your heat pump somehow (perhaps via the connected devices list in your WIFI router etc?) and the serial number of the pump (From alsavo app). Then you can use this app to control various aspects of the pump. This app was mainly meant to be used through home automation systems, so it is not especially user friendly.
