### ISSUE TITLE
How to compil it ?

### ISSUE THREAD

**Issue by urmarcht** [strandborg/AlsavoCtrl#15]
Hi Mikko,

This app looks fantastic!
But unfortunately I'm completely noobs in development. No problem getting the IP address of the heat pump ou playing with the executable,  but ... how to compile it?
I have tryed with g++ under ubuntu and VScode under windows, but I'm completely nonplussed.

Did you plan to provide a pre compiled version? (my target is ubuntu last LTS) Or can you assist with the command line required to make this wonderful code executable? Maybe in a setup section under readme ?
Thanks

**Comment by strandborg** [comment]
The example build system uses cmake, at least version 3.10.

Clone the repository in a directory, and from that directory, run the following commands:
```
mkdir build
cd build
cmake ..
make
```

After those commands you should have a 'AlsavoCtrl' executable in the build dir.
