### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by Minipouch** [strandborg/AlsavoCtrl#16]
Good morning,
I'm on proxmox. can you tell me what vm i need to do to install alsavoctrl?
I am very beginner. THANKS

**Comment by strandborg** [comment]
I updated readme with generic build instructions, copypasted below:

The example build system uses cmake, at least version 3.10. In addition you'll need a C++ compiler (for example g++) installed.

Clone the repository in a directory, and from that directory, run the following commands:
```
mkdir build
cd build
cmake ..
make
```

After those commands you should have a 'AlsavoCtrl' executable in the build dir.
