### ISSUE TITLE
Data turns static

### ISSUE THREAD

**Issue by aeklo** [strandborg/AlsavoCtrl#6]
Very strange observation as I put my heat pump into use some days ago:
It seems somehow that the status data both retrieved from the AlsavoCtrl command, as well as the Alsavo Pro app (Parameter Settings) turns static after having used AlsavoCtrl. I have not dug very far yet as wether this happens only after sending commands from AlsavoCtrl, or by reading status as well. To be exact: All data like in-temp, out-temp, compressor current/freq does not update. If I pull the cord to the heat pump, and restart it, the data updates near real-time in the Alsavo Pro app.
Note: Silent/Smart/Powerful, set-temp and ON/OFF is not affected.

Have you run into this problem, or could you possibly think of a reason for this? Is AlsavoCtrl sending some commands that could possibly disable updating of these data?

**Comment by strandborg** [comment]
I don't think I've seen this exact behavior, but I know that if any commands are sent (either via AlsavoCtrl or the official app) during the defrost cycle, the pump gets confused and loses the wifi connection for a while. But if you say that the on/off, set-temp etc controls are working, then what you are seeing is probably something different.

In general, the pump firmware doesn't seem to be very robust, so anything outside the normal usage patterns can cause loss of connectivity. I reverse-engineered the protocol by observing the network traffic and by looking at the disassembled app code, so any improvements on those would be warmly welcome =)

**Comment by aeklo** [comment]
I did some changes to my network after you mentioned the drop-outs, specificially UAPSD (Unshceduled Automatic Power Save Delivery), which seems to have done the trick. Why the Alsavo values turned static, I don't know, but I guess it might have something to do with the connectivity issue you mention. Seems strange though, that power, set-temp etc. was working. But I'll keep it under observation for some days, and if it works, it works :-)
Thanks!
